# Generated by Django 5.2.7 on 2025-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='country_issued',
            field=models.CharField(max_length=100),
        ),
    ]
